name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: ["main"] # Agar branch ka naam 'master' hai, toh ise 'master' kar dein
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run Build Script
        run: node build.js # Make sure aapki JS file ka yahi naam ho

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Deploys the root directory where the HTML files are generated

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
